name: Tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y fuse3 libfuse-dev

      - name: Unit Tests
        run: cargo test --verbose

  integration-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y fuse3 libfuse-dev

      - name: Build Pinoq
        run: cargo build --release

      - name: Prepare
        run: |
          echo -e 'user_allow_other' | sudo tee -a /etc/fuse.conf
          cp ./target/release/pinoq /usr/local/bin
          mkdir /tmp/pinoq

      - name: Integration Tests
        run: python -W ignore ./tests/integration.py
        env:
          PINOQ_BIN: pinoq
